blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/DerekSeaman/ESPHome-Seeed-Xiao-ESP32-s3-Config/blob/main/README.md
    about: Check the README for configuration examples and documentation
