substitutions:
  device_name: esphomec3-garage
  friendly_name: Garage C3
  api_key: "ZmFrZWFwaWtleWZha2VleGFtcGxlZmFrZWtleQ=="
  ota_password: "ChangeMe!2025"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  device: !include "common/Seeed xiao ESP32-c3 base.yaml"
